name: Spring Boot CICD with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build with Gradle
        working-directory: ./Docker/spring-with-docker
        run: | 
            gradle bootJar
            ls
        
      - uses: actions/upload-artifact@v1
        with:
            name: spring-with-docker
            path: ./Docker/spring-with-docker/build/libs/
      - uses: mr-smithers-excellent/docker-build-push@v5
            name: Build & push Docker image
            with:
              image: ${{ secrets.DOCKER_USERNAME }}/docker-learning
              tags: latest
              registry: docker.io
              dockerfile: Dockerfile
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
       

